apiVersion: apps/v1
kind: Deployment
metadata:
  name: randfoodtravel-container
spec:
  replicas: 5
  selector:
    matchLabels:
      app: randfoodtravel
  template:
    metadata:
      labels:
        app: randfoodtravel
    spec:
      containers:
      - name: randfoodtravel-container
        image: kyk000306/node-web-app:latest # 기본값 설정
        ports:
        - containerPort: 80