apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-webserver
  ports:
    - protocol: TCP
      port: 80         # 외부에서 접근할 포트
      targetPort: 3000 # 컨테이너에서 실행 중인 Node.js 포트
  type: NodePort