name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        mongodbURI: ${{ secrets.mongodbURI }}
        clientId: ${{ secrets.clientID }}
        clientSecret: ${{ secrets.clientSecret }}
        APIKey: ${{ secrets.APIKey }}
        APIKeySecret: ${{ secrets.APIKeySecret }}

    - name: Build Docker image
      run: |
        docker build \
          --build-arg mongodbURI: ${{ secrets.mongodbURI }} \
          --build-arg clientId: ${{ secrets.clientID }} \
          --build-arg clientSecret: ${{ secrets.clientSecret }} \
          --build-arg APIKey: ${{ secrets.APIKey }} \
          --build-arg APIKeySecret: ${{ secrets.APIKeySecret }} \
          -t ${{ secrets.DOCKER_USERNAME }}/node-web-app:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/node-web-app:${{ github.sha }}